POST http://localhost:8080/etudiant/
Authorization: Basic Admin Admin
Content-Type: application/json

{
  "numEtu": "o234567",
  "nom": "Blond",
  "prenom": "Richard"
}

###
POST http://localhost:8080/etudiant/
Authorization: Basic Admin Admin
Content-Type: application/json

{
  "numEtu": "o123456",
  "nom": "Saiah",
  "prenom": "Nadir"
}

###
POST http://localhost:8080/enseignant/
Authorization: Basic Admin Admin
Content-Type: application/json

{
  "idEnseignant": "o4321",
  "nomEns": "Blond",
  "prenomEns": "Lea"
}

###
POST http://localhost:8080/semestre/
Authorization: Basic Admin Admin
Content-Type: application/json

{
  "nomS": "S2"
}

###
POST http://localhost:8080/semestre/
Authorization: Basic Admin Admin
Content-Type: application/json

{
  "nomS": "S1"
}

###
POST http://localhost:8080/module/
Authorization: Basic Admin Admin
Content-Type: application/json

{
  "code": "CodeTest",
  "nomM": "Test et qualite",
  "semestre": "S2"
}

###
POST http://localhost:8080/groupe/
Authorization: Basic Admin Admin
Content-Type: application/json

{
  "nomG": "Groupe4",
  "etudiants": [
    {
      "numEtu": "o234567"
    },
    {
      "numEtu": "o23457"
    }
  ]
}

###
POST http://localhost:8080/SMod/
Authorization: Basic Admin Admin
Content-Type: application/json

{
  "nomSM": "SM1",
  "module": "CodeTest",
  "typeCours": "CM",
  "groupe": "Groupe4",
  "enseignant": "o4321"
}

###
POST http://localhost:8080/salle/
Authorization: Basic Admin Admin
Content-Type: application/json

{
  "nomSalle": "E05"

}

###
POST http://localhost:8080/emargement/
Authorization: Basic Admin Admin
Content-Type: application/json

{
  "heureDebut": "2022-05-10T10:30",
  "heureFin": "2022-05-10T13:30",
  "sousModule": {
    "nomSM": "SM1"
  },
  "salle": {
    "nomSalle": "E05"
  }
}

###
POST http://localhost:8080/emargement/
Authorization: Basic Admin Admin
Content-Type: application/json

{
  "heureDebut": "2022-05-10T14:30",
  "heureFin": "2022-05-10T15:30",
  "sousModule": {
    "nomSM": "SM1"
  },
  "salle": {
    "nomSalle": "E05"
  }
}

###
GET http://localhost:8080/etudiant/
Authorization: Basic Admin Admin

###
GET http://localhost:8080/etudiant/o234567
Authorization: Basic Admin Admin

###
DELETE http://localhost:8080/etudiant/o123qq
Authorization: Basic Admin Admin


###
GET http://localhost:8080/enseignant/o4321
Authorization: Basic Admin Admin

###
DELETE http://localhost:8080/enseignant/o4321
Authorization: Basic Admin Admin

###
GET http://localhost:8080/enseignant/
Authorization: Basic Admin Admin

###
GET http://localhost:8080/semestre/
Authorization: Basic Admin Admin

###
DELETE http://localhost:8080/semestre/S2
Authorization: Basic Admin Admin

###
GET http://localhost:8080/module/
Authorization: Basic Admin Admin

###
PUT http://localhost:8080/module/CodeTest
Authorization: Basic Admin Admin
Content-Type: application/json

{
  "nomM": "Test et qualite",
  "semestre":{
    "nomS": "S1"
  }
}

###
GET http://localhost:8080/groupe/
Authorization: Basic Admin Admin

###
GET http://localhost:8080/emargement/168fd113-5370-4a35-8046-1df0f051c1b8
Authorization: Basic p.n@etu.univ-orleans.fr o123

###
GET http://localhost:8080/emargement/QR/168fd113-5370-4a35-8046-1df0f051c1b8
Authorization: Basic p.n@etu.univ-orleans.fr o123
###
GET localhost:8080/emargement/168fd113-5370-4a35-8046-1df0f051c1b8/2c4420cca8689c3cecfa3ecfeb21a1d6
Authorization: Basic p.n@etu.univ-orleans.fr o123
###
GET http://localhost:8080/emargement/ouverts
Authorization: Basic Admin Admin

###
GET http://localhost:8080/emargement/clos
Authorization: Basic Admin Admin

###
GET http://localhost:8080/emargement/QR/acc6773b-8ba6-45af-a753-ae8f81219fa3
Authorization: Basic Jean.Richard@etu.univ-orleans.fr o234567

###
GET http://localhost:8080/emargement/QR/acc6773b-8ba6-45af-a753-ae8f81219fa3
Authorization: Basic Lea.Blond@univ-orleans.fr Blond

###
GET http://localhost:8080/emargement/acc6773b-8ba6-45af-a753-ae8f81219fa3/d8b06b47a04b3bce337f078bf73d7277
Authorization: Basic Lea.Blond@univ-orleans.fr Blond

###
GET http://localhost:8080/emargement/QR/bf2317bf-49f7-4317-82be-cb10bb6bb666
Authorization: Basic Jean.Richard@etu.univ-orleans.fr o234567

###
GET http://localhost:8080/emargement/bf2317bf-49f7-4317-82be-cb10bb6bb666/bbfbc1697ad835e4dcf5243a52857ad7
Authorization: Basic Jean.Richard@etu.univ-orleans.fr o234567

###
GET http://localhost:8080/emargement/
Authorization: Basic Admin Admin



