GET http://localhost:8080/etudiant/

###
GET http://localhost:8080/etudiant/o212121

###
DELETE http://localhost:8080/etudiant/o1234

###
POST http://localhost:8080/etudiant/
Content-Type: application/json

{
  "numEtu": "o23312",
  "nom": "No",
  "prenom": "Pre"
}

###
POST http://localhost:8080/enseignant/
Content-Type: application/json

{
  "idEnseignant": "o212121",
  "nomEns": "Prenom12",
  "prenomEns": "Nom12"
}
###
GET http://localhost:8080/enseignant/o212121

###
DELETE http://localhost:8080/enseignant/o212121

###
GET http://localhost:8080/enseignant/


###
POST http://localhost:8080/semestre/
Content-Type: application/json

{
  "nomS": "S2"
}

###
GET http://localhost:8080/semestre/

###
DELETE http://localhost:8080/semestre/S2


###
GET http://localhost:8080/module/

###
POST http://localhost:8080/module/
Content-Type: application/json

{
  "code": "CodeTest",
  "nomM": "Test et qualite",
  "semestre": "S2"
}
###
PUT http://localhost:8080/module/Code1
Content-Type: application/json

{
  "nomM": "Module3",
  "semestre":{
    "nomS": "S1"
  }
}

###
POST http://localhost:8080/SMod/
Content-Type: application/json

{
  "nomSM": "Module4",
  "module": "CodeTest",
  "typeCours": "CM",
  "groupe": "Module4",
  "enseignant": "o212121"
}
###
GET http://localhost:8080/groupe/


###
POST http://localhost:8080/groupe/
Content-Type: application/json

{
  "nomG": "Module4",
  "etudiants": [
    {
      "numEtu": "o23312"
    },
    {
      "numEtu": "o212121"
    }
  ]
}
